services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: popcorn-palace
      POSTGRES_PASSWORD: popcorn-palace
      POSTGRES_DB: popcorn-palace
  #  volumes:
   #   - type: bind
   #     source: ./data
   #     target: /var/lib/postgresql/data --> in case u need to save data to local storage
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  postgres-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: popcorn_palace_test
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
